[package]
name = "tazmondo/rumble-rojo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@^1.15.6"
Loader = "sleitnick/loader@^2.0.0"
TableUtil = "sleitnick/table-util@^1.2.0"
RaycastHitbox = "ulferno/raycasthitbox@^4.0.1"
Cmdr = "evaera/cmdr@^1.12.0"

Red = "red-blox/red@2.1.0"
Future = "red-blox/future@^1.0.1"
Guard = "red-blox/guard@^1.0.0"
Signal = "red-blox/signal@^2.0.0"
Bin = "red-blox/bin@^1.0.0"
Spawn = "red-blox/spawn@^1.0.0"
